<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>ripmedia</AssemblyName>
    <RootNamespace>Ripmedia.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ripmedia.Core\Ripmedia.Core.csproj" />
    <PackageReference Include="Spectre.Console" Version="0.49.1" />
  </ItemGroup>
</Project>
